console.log('Testing merge')
console.log("2nd line added")
console.log("2nd line added")
console.log("2nd line added")
console.log('Testing merge')
console.log("2nd line added")
console.log("7th line added")
console.log("7th line changed")